spring:
  application:
    name: tj-pring-cloud-zuul
  zipkin:
    base-url: http://localhost:8768
  boot:
    admin:
      client:
        url: http://localhost:8700

server:
  port: 8766

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
     api-a:
        path: /api/a/**
        serviceId: tj-spring-cloud-web-admin-feign
     api-b:
        path: /api/b/**
        serviceId: tj-spring-cloud-web-andim-ribbon