spring:
  application:
    name: tj-spring-cloud-admin
  zipkin:
    base-url: http://localhost:8768

server:
  port: 8700


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]