spring:
  application:
    name: tj-spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8700

server:
  port: 8768

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false