spring:
  application:
    name: tj-spring-cloud-service-admin
  zipkin:
    base-url: http://localhost:8768
  boot:
    admin:
      client:
        url: http://localhost:8700

server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/